---
- hosts: tier1
  become: true
  vars_files: vars_file.yml
  name: Installing and starting {{ install_pkg }} server
  tasks:
  - set_fact:
      srvtype: "ftp"
      ssh_port: "22"
      ftp_port: "20"
  
  - name: Installing {{ srvtype }} server
    package:   
      name: "{{ install_pkg }}"
      state: latest
  
  - name: Starting {{ srvtype }} server process
    service:
      name: "{{ install_pkg }}"    
      state: started
      enabled: true

  - name: Installing firewall {{ firewall_pkg }} on Debian
    package:
      name: "{{ firewall_pkg }}"
      state: latest
    when: ansible_distribution == 'Debian'

  - name: Enable SSH port on Debian firewall
    ufw:
      rule: allow
      port: "{{ ssh_port }}"
    when: ansible_distribution == 'Debian'
  
  - name: Starting {{ firewall_pkg }} firewall on Debian
    service:
      name: "{{ firewall_pkg }}"
      state: started
      enabled: true  
    when: ansible_distribution == 'Debian'
    
  - name: Add {{ srvtype }} service to permited on {{ firewall_pkg }} firewall
    ufw:      
      rule: allow
      port: "{{ ftp_port }}"
    when: ansible_distribution == 'Debian'

  - name: Starting firewall daemon on CentOS
    service:
      name: firewalld
      enabled: true
      state: started
    when: ansible_distribution == 'CentOS'

  - name: Add {{ srvtype }} port on CentOS firewall to permited rules
    firewalld:
      state: enabled
      service: "{{ srvtype }}"
      immediate: yes
      permanent: yes
    when: ansible_distribution == 'CentOS'


    
